PATH_TO_DOTFILES="/dotfiles/stowed-files/picom/.config/picom"
IMPORT_LOCATION="$HOME$PATH_TO_DOTFILES"
CONFIG_LOCATION="/.config/picom"
EXPORT_LOCATION="$HOME$CONFIG_LOCATION"

mkdir -p $EXPORT_LOCATION
echo "Copying picom files to $EXPORT_LOCATION"
cp -Rf $IMPORT_LOCATION/* $EXPORT_LOCATION/

