PATH_TO_DOTFILES="/dotfiles/stowed-files/qtile/.config/qtile"
IMPORT_LOCATION="$HOME$PATH_TO_DOTFILES"
CONFIG_LOCATION="/.config/qtile"
EXPORT_LOCATION="$HOME$CONFIG_LOCATION"

mkdir -p $EXPORT_LOCATION
echo "Copying qtile files to $EXPORT_LOCATION"
cp -Rf $IMPORT_LOCATION/* $EXPORT_LOCATION/

